#!/usr/bin/env bash
## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init
##
# Initialize stack
fin project start
# Install project requirements
fin exec composer clear-cache
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec composer install
# Set up blt
fin blt blt:init:git-hooks
fin blt blt:init:settings
# Sync local db and files to remote
fin sync dev
