module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  allowed_formats: 0
  automated_cron: 0
  better_exposed_filters: 0
  bg_image_formatter: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  classy_paragraphs: 0
  color: 0
  config: 0
  config_export_ignore: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  editor_file: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  field: 0
  field_group: 0
  field_group_settings: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_resmushit: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  link_class: 0
  linkit: 0
  login_emailusername: 0
  mailsystem: 0
  media: 0
  media_library: 0
  media_responsive_thumbnail: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_component_field: 0
  path: 0
  path_alias: 0
  permissions_filter: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  robotstxt: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  smart_trim: 0
  system: 0
  taxonomy: 0
  telephone: 0
  telephone_formatter: 0
  telephone_validation: 0
  text: 0
  theme_filter: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  viewsreference: 0
  limited_field_widgets: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  blackbird: 1000
theme:
  bartik: 0
  seven: 0
profile: blackbird
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
